name: Post Random Bot

on:
  schedule:
    - cron: '13 * * * *'   # 8 AM EST
    - cron: '19 * * * *'   # 2 PM EST
    - cron: '1  * * * *'   # 8 PM EST (next day UTC)

jobs:
  post-random:
    runs-on: ubuntu-latest

    steps:
      - name: Call post-random endpoint
        run: |
          curl -X POST "https://amateur-oracle-bot.vercel.app/api/post-random" \
            -H "Authorization: Bearer ${{ secrets.API_AUTH_TOKEN }}" \
            -H "Content-Type: application/json"

